// アプリで使う画像の出典（写真は撮影者・ライセンス・元の場所、AI の画像は生成に使ったモデルとプロンプトの要旨）。
// 「写真の出典」ページ（app/credits）がこれを表示する。
// 画像を足したら、public/images/ にファイルを置き、supabase/seed.sql の image_path と、ここに1件ずつ足す。
// CC BY・CC BY-SA は、撮影者・ライセンス・元の題名を見る人に分かる形で示すことが条件なので、必ずここに書く（#67）
// 許可のいらない写真が見つからないスポットは、AI で生成したイメージ画像を使い、画面で「イメージ（AI で生成）」と示す（#146）

export type PhotoCredit = {
  kind: "photo";
  /** public/ からのパス（spots.image_path と同じ値） */
  path: string;
  /** 写っているもの（スポット名） */
  subject: string;
  /**
   * 元の写真の題名。CC BY・CC BY-SA は題名が付いていれば表示を求めるので、必ず書く。
   * Flickr は写真のページの題名、Commons はファイルページの名前（`File:` を除き、`_` を空白にしたもの）、
   * VIEW OF KAMIKAWA は写真のページの「題名」
   */
  title: string;
  /** 撮影者（元の写真のページの表記。VIEW OF KAMIKAWA は職員が撮影しているので、公開している北海道上川総合振興局） */
  author: string;
  /** ライセンスの短い名前 */
  license: string;
  /** ライセンスの本文。パブリックドメインは null */
  licenseUrl: string | null;
  /** 元の写真のページ */
  sourceUrl: string;
  /**
   * 元の写真を公開しているサイト。VIEW OF KAMIKAWA は北海道上川総合振興局の写真集で、
   * 北海道のサイトポリシーにより CC BY 4.0（#146。使ったあとに画像の番号などを知らせてほしいというお願いがある）
   */
  sourceName: "Wikimedia Commons" | "Flickr" | typeof VIEW_OF_KAMIKAWA;
};

/**
 * AI で生成したイメージ画像。ほかの写真と並んでも浮かないよう写真調にし（#158）、実在の店や施設の外観・看板・特定の建物・人物の顔は再現しない。
 * 写真と見分けられるよう、画面では必ず「イメージ（AI で生成）」と示す。
 * path は AI_IMAGE_DIR（lib/spots/image-kind.ts）の下に置く（画面はパスで「イメージ（AI で生成）」を出すかを決める）
 */
export type AiImageCredit = {
  kind: "ai";
  /** public/ からのパス（spots.image_path と同じ値）。AI_IMAGE_DIR の下 */
  path: string;
  /** 表しているもの（スポット名） */
  subject: string;
  /** 生成に使ったモデル（例: "Gemini 2.5 Flash Image"） */
  model: string;
  /** プロンプトの要旨（「写真の出典」ページに出す） */
  prompt: string;
  /** 生成した日（YYYY-MM-DD） */
  createdOn: string;
};

export type ImageCredit = PhotoCredit | AiImageCredit;

/** 元の写真からの変更。CC BY・CC BY-SA では、変更したことを示す */
export const PHOTO_CHANGES = "長辺を1200px以下に縮小し、JPEG で圧縮した";

const BY_2 = "https://creativecommons.org/licenses/by/2.0";
const BY_2_5 = "https://creativecommons.org/licenses/by/2.5";
const BY_3 = "https://creativecommons.org/licenses/by/3.0";
const BY_4 = "https://creativecommons.org/licenses/by/4.0";
const BY_SA_2 = "https://creativecommons.org/licenses/by-sa/2.0";
const BY_SA_3 = "https://creativecommons.org/licenses/by-sa/3.0";
const BY_SA_4 = "https://creativecommons.org/licenses/by-sa/4.0";
const CC0 = "https://creativecommons.org/publicdomain/zero/1.0";
const COMMONS = "https://commons.wikimedia.org/wiki/File:";
const FLICKR = "https://www.flickr.com/photos/";
const KAMIKAWA_ALBUM = "https://www.kamikawa.pref.hokkaido.lg.jp/ts/tss/album/";
const KAMIKAWA = "北海道上川総合振興局";
export const VIEW_OF_KAMIKAWA = "北海道の風景～VIEW OF KAMIKAWA～";

/** AI の画像を作ったモデル（#158。ChatGPT のアカウントでログインした Codex CLI の組み込みの画像生成） */
const AI_MODEL = "OpenAI の画像生成（Codex CLI の image_gen）";

export const PHOTO_CREDITS: PhotoCredit[] = [
  {
    kind: "photo",
    path: "/images/spots/hakuba-01.jpg",
    subject: "白馬塩の道温泉 倉下の湯",
    title: "Kurashita no yu.jpg",
    author: "Qurren",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Kurashita_no_yu.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/hakuba-02.jpg",
    subject: "青鬼集落",
    title: "青鬼集落 - panoramio.jpg",
    author: "くろふね",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E9%9D%92%E9%AC%BC%E9%9B%86%E8%90%BD_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/hakuba-03.jpg",
    subject: "大出公園",
    title: "大出吊橋 - panoramio (4).jpg",
    author: "くろふね",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E5%A4%A7%E5%87%BA%E5%90%8A%E6%A9%8B_-_panoramio_(4).jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/hakuba-04.jpg",
    subject: "姫川源流自然探勝園",
    title: "姫川源流 - panoramio.jpg",
    author: "くろふね",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E5%A7%AB%E5%B7%9D%E6%BA%90%E6%B5%81_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/hakuba-06.jpg",
    subject: "貞麟寺",
    title: "桜@貞麟寺",
    author: "wakaba-shinshu",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${FLICKR}154568645@N04/34658438162`,
    sourceName: "Flickr",
  },
  {
    kind: "photo",
    path: "/images/spots/omachi-01.jpg",
    subject: "塩の道ちょうじや",
    title: "Hirabayashi-ke Jyutaku Shuoku.jpg",
    author: "Suikotei",
    license: "CC BY 4.0",
    licenseUrl: BY_4,
    sourceUrl: `${COMMONS}Hirabayashi-ke_Jyutaku_Shuoku.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/omachi-02.jpg",
    subject: "若一王子神社",
    title: "若一王子神社鳥居と三重塔.jpg",
    author: "Furudanuki",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}%E8%8B%A5%E4%B8%80%E7%8E%8B%E5%AD%90%E7%A5%9E%E7%A4%BE%E9%B3%A5%E5%B1%85%E3%81%A8%E4%B8%89%E9%87%8D%E5%A1%94.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/omachi-03.jpg",
    subject: "ぽかぽかランド美麻",
    title: "Road Station Poka-Poka Land Miasa 01.jpg",
    author: "小石川人晃",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Road_Station_Poka-Poka_Land_Miasa_01.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/omachi-06.jpg",
    subject: "居谷里湿原",
    title: "リュウキンカ@居谷里湿原",
    author: "wakaba-shinshu",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${FLICKR}154568645@N04/34011672963`,
    sourceName: "Flickr",
  },
  {
    kind: "photo",
    path: "/images/spots/omachi-07.jpg",
    subject: "中綱湖",
    title: "中綱湖 - panoramio.jpg",
    author: "くろふね",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E4%B8%AD%E7%B6%B1%E6%B9%96_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/omachi-08.jpg",
    subject: "鷹狩山",
    title: "Japan North Alps",
    author: "wakanmuri",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${FLICKR}13217899@N08/3507257327`,
    sourceName: "Flickr",
  },
  {
    kind: "photo",
    path: "/images/spots/ikeda-01.jpg",
    subject: "池田八幡神社",
    title: "池田八幡神社社殿.jpg",
    author: "At1973",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}%E6%B1%A0%E7%94%B0%E5%85%AB%E5%B9%A1%E7%A5%9E%E7%A4%BE%E7%A4%BE%E6%AE%BF.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/ikeda-04.jpg",
    subject: "夢農場",
    title: "桜@池田町 夢農場",
    author: "wakaba-shinshu",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${FLICKR}154568645@N04/34840653796`,
    sourceName: "Flickr",
  },
  {
    kind: "photo",
    path: "/images/spots/ikeda-05.jpg",
    subject: "花紋大雪渓",
    title: "Daisekkei Sake Brewing 1.jpg",
    author: "Qurren",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Daisekkei_Sake_Brewing_1.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/azumino-02.jpg",
    subject: "ほりでーゆ〜四季の郷",
    title: "Holiday You Shikinosato.jpg",
    author: "Qurren",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Holiday_You_Shikinosato.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/azumino-04.jpg",
    subject: "貞享義民記念館",
    title: "Kinenkan.JPG",
    author: "小松宏彰",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}Kinenkan.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/azumino-06.jpg",
    subject: "御宝田遊水池",
    title: "御宝田遊水池.jpg",
    author: "アポロ2",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}%E5%BE%A1%E5%AE%9D%E7%94%B0%E9%81%8A%E6%B0%B4%E6%B1%A0.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/azumino-07.jpg",
    subject: "烏川渓谷緑地",
    title: "Karasu River view from Karasugawakeikokubashi-bridge.jpg",
    author: "Qurren",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Karasu_River_view_from_Karasugawakeikokubashi-bridge.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/matsumoto-01.jpg",
    subject: "松本市はかり資料館",
    title:
      "250425 Matsumoto City Hakari Museum Matsumoto Nagano pref Japan01s3.jpg",
    author: "663highland",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}250425_Matsumoto_City_Hakari_Museum_Matsumoto_Nagano_pref_Japan01s3.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/matsumoto-05.jpg",
    subject: "源智の井戸",
    title: "源智の井戸.jpg",
    author: "深志",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}%E6%BA%90%E6%99%BA%E3%81%AE%E4%BA%95%E6%88%B8.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/matsumoto-06.jpg",
    subject: "馬場家住宅",
    title: "Babake house 2010.jpg",
    author: "Wiiii",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Babake_house_2010.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/matsumoto-07.jpg",
    subject: "弘法山古墳",
    title: "Koboyama Kofun zenkei.JPG",
    author: "Saigen Jiro",
    license: "CC0",
    licenseUrl: CC0,
    sourceUrl: `${COMMONS}Koboyama_Kofun_zenkei.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/higashikawa-01.jpg",
    subject: "旭岳",
    title: "Asahi-dake (9099317042).jpg",
    author: "nAok0",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${COMMONS}Asahi-dake_(9099317042).jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/higashikawa-02.jpg",
    subject: "忠別湖",
    title: "忠別湖（Lake Tyubetsu） - panoramio.jpg",
    author: "pakku",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E5%BF%A0%E5%88%A5%E6%B9%96%EF%BC%88Lake_Tyubetsu%EF%BC%89_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/higashikawa-03.jpg",
    subject: "キトウシの森",
    title: "スプリング・エフェメラル２",
    author: KAMIKAWA,
    license: "CC BY 4.0",
    licenseUrl: BY_4,
    sourceUrl: `${KAMIKAWA_ALBUM}life/133087.html`,
    sourceName: VIEW_OF_KAMIKAWA,
  },
  {
    kind: "photo",
    path: "/images/spots/higashikawa-04.jpg",
    subject: "大雪旭岳源水",
    title: "旭岳源水",
    author: KAMIKAWA,
    license: "CC BY 4.0",
    licenseUrl: BY_4,
    sourceUrl: `${KAMIKAWA_ALBUM}view/133653.html`,
    sourceName: VIEW_OF_KAMIKAWA,
  },
  {
    kind: "photo",
    path: "/images/spots/higashikawa-05.jpg",
    subject: "北の住まい設計社",
    title: "北の住まい設計社１",
    author: KAMIKAWA,
    license: "CC BY 4.0",
    licenseUrl: BY_4,
    sourceUrl: `${KAMIKAWA_ALBUM}structure/132066.html`,
    sourceName: VIEW_OF_KAMIKAWA,
  },
  {
    kind: "photo",
    path: "/images/spots/marumori-01.jpg",
    subject: "蔵の郷土館 齋理屋敷",
    title: "Sairi Residence storehouse.jpg",
    author: "Mukasora",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Sairi_Residence_storehouse.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/nakanojo-02.jpg",
    subject: "奥四万湖",
    title: "Shimagawa Dam-Lake.jpg",
    author: "Neruru",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}Shimagawa_Dam-Lake.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/nakanojo-03.jpg",
    subject: "沢渡温泉 共同浴場",
    title: "Sawatari Onsen public bath.jpg",
    author: "Qurren",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Sawatari_Onsen_public_bath.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/nakanojo-04.jpg",
    subject: "旧太子駅",
    title: "Oshi Station 2017-08 1.jpg",
    author: "Qurren",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Oshi_Station_2017-08_1.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/nakanojo-05.jpg",
    subject: "野反湖",
    title: "Lake Nozori 2011-07-23 (5989960888).jpg",
    author: "Kohei Fujii",
    license: "CC BY-SA 2.0",
    licenseUrl: BY_SA_2,
    sourceUrl: `${COMMONS}Lake_Nozori_2011-07-23_(5989960888).jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/nakanojo-06.jpg",
    subject: "道の駅 霊山たけやま",
    title: "R145-2020-102.jpg",
    author: "Puchi-masashi",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}R145-2020-102.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/ono-01.jpg",
    subject: "御清水",
    title: "Echizen-Ono Oshozu 2021-07 ac.jpg",
    author: "Asturio Cantabrio",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Echizen-Ono_Oshozu_2021-07_ac.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/ono-02.jpg",
    subject: "武家屋敷旧内山家",
    title: "Former Uchiyama House 2021-07 ac.jpg",
    author: "Asturio Cantabrio",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Former_Uchiyama_House_2021-07_ac.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/ono-03.jpg",
    subject: "亀山湯",
    title: "Echizen-Ono Kameyama-yu 2021-07 ac.jpg",
    author: "Asturio Cantabrio",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Echizen-Ono_Kameyama-yu_2021-07_ac.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/ono-04.jpg",
    subject: "真名鶴酒造",
    title: "Manatsuru Brewery 2021-07 ac.jpg",
    author: "Asturio Cantabrio",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Manatsuru_Brewery_2021-07_ac.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/ono-05.jpg",
    subject: "六呂師高原",
    title: "Rokuroshi Highland s2.jpg",
    author: "Alpsdake",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Rokuroshi_Highland_s2.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/ono-06.jpg",
    subject: "越前大野城",
    title: "Echizen Ono Castle.jpg",
    author: "Keisuke MAEDA",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Echizen_Ono_Castle.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takashima-01.jpg",
    subject: "白鬚神社",
    title: "Shirahige-jinja (Takashima) otorii.JPG",
    author: "Saigen Jiro",
    license: "CC0",
    licenseUrl: CC0,
    sourceUrl: `${COMMONS}Shirahige-jinja_(Takashima)_otorii.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takashima-02.jpg",
    subject: "メタセコイア並木",
    title: "Metasequoia Namiki in 2019.jpg",
    author: "Saigen Jiro",
    license: "CC0",
    licenseUrl: CC0,
    sourceUrl: `${COMMONS}Metasequoia_Namiki_in_2019.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takashima-03.jpg",
    subject: "針江生水の郷",
    title: "Harie20160508a.JPG",
    author: "Kyoww",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Harie20160508a.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takashima-04.jpg",
    subject: "道の駅 くつき新本陣",
    title: "Michinoeki Kutsuki Shinhonjin 20220228 03.jpg",
    author: "先従隗始",
    license: "CC0",
    licenseUrl: CC0,
    sourceUrl: `${COMMONS}Michinoeki_Kutsuki_Shinhonjin_20220228_03.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takahashi-01.jpg",
    subject: "備中松山城",
    title: "BitchuMatsuyamaCastleKeep Takahashi Okayama Japan 2015.jpg",
    author: "Ka23 13",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}BitchuMatsuyamaCastleKeep_Takahashi_Okayama_Japan_2015.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takahashi-02.jpg",
    subject: "吹屋ふるさと村",
    title: "高梁市 吹屋ふるさと村 - panoramio.jpg",
    author: "Yoshio Kohara",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E9%AB%98%E6%A2%81%E5%B8%82_%E5%90%B9%E5%B1%8B%E3%81%B5%E3%82%8B%E3%81%95%E3%81%A8%E6%9D%91_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takahashi-03.jpg",
    subject: "ベンガラ館",
    title: "Bengarakan07s3200.jpg",
    author: "663highland",
    license: "CC BY 2.5",
    licenseUrl: BY_2_5,
    sourceUrl: `${COMMONS}Bengarakan07s3200.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takahashi-04.jpg",
    subject: "頼久寺庭園",
    title: "Raikyuji 20180502 112529.jpg",
    author: "Ka23 13",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Raikyuji_20180502_112529.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/takahashi-05.jpg",
    subject: "弥高山公園",
    title: "Yatakayama-unkai002.jpg",
    author: "じぇい☆",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Yatakayama-unkai002.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/taketa-01.jpg",
    subject: "岡城跡",
    title: "Okajoshi.jpg",
    author: "As6673",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}Okajoshi.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/taketa-02.jpg",
    subject: "白水ダム",
    title: "Hakusui-Dam full-view.jpg",
    author: "Tmizuk",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}Hakusui-Dam_full-view.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/taketa-03.jpg",
    subject: "七里田温泉館",
    title: "七里田温泉下湯 - panoramio.jpg",
    author: "sk01",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}%E4%B8%83%E9%87%8C%E7%94%B0%E6%B8%A9%E6%B3%89%E4%B8%8B%E6%B9%AF_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/taketa-05.jpg",
    subject: "ラムネ温泉館",
    title: "ラムネ温泉 - panoramio.jpg",
    author: "sk01",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}%E3%83%A9%E3%83%A0%E3%83%8D%E6%B8%A9%E6%B3%89_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/taketa-06.jpg",
    subject: "くじゅう花公園",
    title: "Kuju Flower Park(3553982332).jpg",
    author: "TANAKA Juuyoh (田中十洋)",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${COMMONS}Kuju_Flower_Park(3553982332).jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/tono-01.jpg",
    subject: "荒川高原牧場",
    title: "荒川高原牧場 03.jpg",
    author: "Indiana jo",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}%E8%8D%92%E5%B7%9D%E9%AB%98%E5%8E%9F%E7%89%A7%E5%A0%B4_03.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/tono-02.jpg",
    subject: "続石",
    title: "続石.jpg",
    author: "Ty19080914",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}%E7%B6%9A%E7%9F%B3.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/tono-03.jpg",
    subject: "五百羅漢",
    title: "Tono 500rakan02s3872.jpg",
    author: "663highland",
    license: "CC BY 2.5",
    licenseUrl: BY_2_5,
    sourceUrl: `${COMMONS}Tono_500rakan02s3872.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/tono-06.jpg",
    subject: "道の駅 遠野風の丘",
    title: "Michinoeki Tono.JPG",
    author: "アラツク",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Michinoeki_Tono.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/tsuwano-01.jpg",
    subject: "津和野城跡",
    title: "TsuwanoJo.JPG",
    author: "Mocchy",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}TsuwanoJo.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/tsuwano-02.jpg",
    subject: "太皷谷稲成神社",
    title: "Taikodani Inari-jinja (559443222).jpg",
    author: "sean from Osaka, Japan",
    license: "CC BY-SA 2.0",
    licenseUrl: BY_SA_2,
    sourceUrl: `${COMMONS}Taikodani_Inari-jinja_(559443222).jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/tsuwano-04.jpg",
    subject: "古橋酒造",
    title: "Furuhashi Brewery in Tsuwano-cho, Kanoashi-gun, Shimane 001.jpg",
    author: "Naokijp",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Furuhashi_Brewery_in_Tsuwano-cho,_Kanoashi-gun,_Shimane_001.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    kind: "photo",
    path: "/images/spots/tsuwano-06.jpg",
    subject: "道の駅 津和野温泉 なごみの里",
    title: "Michinoeki Tsuwano-onsen.JPG",
    author: "アラツク",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Michinoeki_Tsuwano-onsen.JPG`,
    sourceName: "Wikimedia Commons",
  },
];

/** AI で生成したイメージ画像。許可のいらない写真が見つからなかったスポットに使う（#146。探した結果は docs/image-credits.md） */
export const AI_IMAGE_CREDITS: AiImageCredit[] = [
  {
    kind: "ai",
    path: "/images/spots/ai/hakuba-05.jpg",
    subject: "白馬ガラス工房GAKU",
    model: AI_MODEL,
    prompt:
      "ガラス工房の作業台に並ぶ色とりどりのとんぼ玉と、ガラス棒・バーナー（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/hakuba-07.jpg",
    subject: "おやきの山愛",
    model: AI_MODEL,
    prompt:
      "木のテーブルの上の焼き目のついたおやき（1つは割って野沢菜の具）と緑茶、窓の外に初夏の山並み",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/hakuba-08.jpg",
    subject: "Kitchen＆Marché 農かふぇ",
    model: AI_MODEL,
    prompt:
      "テラス席のテーブルの夏野菜のスープカレーとごはん、背景に初夏の田畑と山並み",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/omachi-04.jpg",
    subject: "ゆいせきや",
    model: AI_MODEL,
    prompt:
      "古い木の机の上の、柿渋を塗った一閑張りのカゴと小物入れ、刷毛と和紙（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/omachi-05.jpg",
    subject: "創舎 わちがい",
    model: AI_MODEL,
    prompt:
      "古い屋敷の座敷の塗りの膳に並ぶ郷土料理（山菜の煮物・川魚の塩焼き・炊き込みごはんなど）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/ikeda-02.jpg",
    subject: "あづみ野池田クラフトパーク",
    model: AI_MODEL,
    prompt:
      "丘の上の公園の芝生と満開の桜の向こうに、安曇野の田園と残雪の北アルプス（春の夕方前）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/ikeda-03.jpg",
    subject: "北アルプス展望美術館",
    model: AI_MODEL,
    prompt: "丘の上から見渡す、初夏の安曇野の田園と残雪の北アルプス",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/ikeda-06.jpg",
    subject: "カフェ風のいろ",
    model: AI_MODEL,
    prompt:
      "窓辺の席のハンドドリップのコーヒーと焼き菓子、窓の外に初夏の庭と田園",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/ikeda-07.jpg",
    subject: "HOP FROG CAFE",
    model: AI_MODEL,
    prompt:
      "カウンターに並ぶ味見用のクラフトビールのグラスと浅煎りのコーヒー、小皿の料理",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/ikeda-08.jpg",
    subject: "発酵と暮らし おはこ",
    model: AI_MODEL,
    prompt:
      "古民家の食堂の発酵ごはんの定食（玄米・味噌汁・ぬか漬け・果実のシロップのソーダ）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/azumino-01.jpg",
    subject: "豊科温泉 湯多里山の神",
    model: AI_MODEL,
    prompt: "自然石で囲んだ露天の岩風呂と、竹の垣根の向こうの初夏の丘",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/azumino-03.jpg",
    subject: "安曇野市天蚕センター",
    model: AI_MODEL,
    prompt:
      "クヌギの葉の間についた天蚕の淡い黄緑色の繭と、天蚕糸のかせ（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/azumino-05.jpg",
    subject: "長峰山",
    model: AI_MODEL,
    prompt:
      "山頂の草地と山桜の向こうに、安曇野の田園と川の合流、残雪の北アルプス（春の夕方前）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/azumino-08.jpg",
    subject: "三郷サラダ市",
    model: AI_MODEL,
    prompt: "直売所の台に並ぶ、かごに盛ったりんご・梨・ぶどう（秋の朝）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/matsumoto-02.jpg",
    subject: "ホットプラザ浅間",
    model: AI_MODEL,
    prompt: "石で囲んだ露天風呂と、竹の垣根の向こうの初夏の山の稜線",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/matsumoto-03.jpg",
    subject: "手仕事商會 すぐり",
    model: AI_MODEL,
    prompt:
      "古い蔵の中の机に並ぶ、草木染めの糸でかがった松本てまりと糸の束（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/matsumoto-04.jpg",
    subject: "ファーマーズガーデンうちだ",
    model: AI_MODEL,
    prompt:
      "直売所の台の採れたての夏野菜と卵の向こうに、松本平と残雪の北アルプス（初夏の朝）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/matsumoto-08.jpg",
    subject: "城山公園",
    model: AI_MODEL,
    prompt: "丘の上の満開の桜の向こうに、松本の市街地と残雪の北アルプス（春）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/higashikawa-06.jpg",
    subject: "平田とうふ店",
    model: AI_MODEL,
    prompt: "皿にのった大きな木綿豆腐と、水槽の豆腐・醤油と刻みねぎ（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/marumori-02.jpg",
    subject: "阿武隈ライン舟下り",
    model: AI_MODEL,
    prompt: "秋の阿武隈川の渓谷と紅葉の山肌、遠くに浮かぶ屋根のない川舟",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/marumori-03.jpg",
    subject: "不動尊公園",
    model: AI_MODEL,
    prompt: "岩の間を流れる渓流と、川岸に並ぶ満開の桜、新緑の山（春）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/marumori-04.jpg",
    subject: "百々石公園",
    model: AI_MODEL,
    prompt:
      "丘の上の桜とツツジの向こうに、川と小さな町並み、遠くの残雪の山並み（春）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/marumori-05.jpg",
    subject: "ラーメンきく屋",
    model: AI_MODEL,
    prompt:
      "白い丼の澄んだ醤油色のスープの中華そば（細麺・チャーシュー・メンマ・ねぎ・海苔）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/marumori-06.jpg",
    subject: "西円寺（猫神さま）",
    model: AI_MODEL,
    prompt: "寺の境内の片隅の、猫の姿を浮き彫りにした苔むした古い石碑（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/nakanojo-01.jpg",
    subject: "日向見薬師堂",
    model: AI_MODEL,
    prompt: "杉の大木の木立の中を上へ続く、苔むした石段と小さな石灯籠（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/takashima-05.jpg",
    subject: "高島びれっじ",
    model: AI_MODEL,
    prompt:
      "古い商家の土間と木の梁、棚に並ぶ手作りのキャンドルとハーバリウム（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/takashima-06.jpg",
    subject: "ホソイフクロモノ",
    model: AI_MODEL,
    prompt:
      "作業台の上の綿帆布と麻織物、帆布のトートバッグと裁ちばさみ、奥にミシン（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/takahashi-06.jpg",
    subject: "中野 実りの直売所",
    model: AI_MODEL,
    prompt:
      "山あいの直売所の台に並ぶ、かごに盛った季節の野菜と果物、奥に古い石垣（初夏）",
    createdOn: "2026-09-26",
  },
  {
    kind: "ai",
    path: "/images/spots/ai/taketa-04.jpg",
    subject: "小津留湧水",
    model: AI_MODEL,
    prompt: "石で囲った池に澄んだ水が湧き、石の水路へ流れ出る湧き水（初夏）",
    createdOn: "2026-09-26",
  },
];

/** 写真と AI の画像のすべて（パスで引くとき・シードとの突き合わせ） */
export const IMAGE_CREDITS: ImageCredit[] = [
  ...PHOTO_CREDITS,
  ...AI_IMAGE_CREDITS,
];
