// アプリで使う写真の出典（撮影者・ライセンス・元の場所）。「写真の出典」ページ（app/credits）がこれを表示する。
// 写真を足したら、public/images/ にファイルを置き、supabase/seed.sql の image_path と、ここに1件ずつ足す。
// CC BY・CC BY-SA は、撮影者とライセンスを見る人に分かる形で示すことが条件なので、必ずここに書く（#67）

export type PhotoCredit = {
  /** public/ からのパス（spots.image_path と同じ値） */
  path: string;
  /** 写っているもの（スポット名） */
  subject: string;
  /** 撮影者（元の写真のページの表記） */
  author: string;
  /** ライセンスの短い名前 */
  license: string;
  /** ライセンスの本文。パブリックドメインは null */
  licenseUrl: string | null;
  /** 元の写真のページ */
  sourceUrl: string;
  /** 元の写真を公開しているサイト */
  sourceName: "Wikimedia Commons" | "Flickr";
};

/** 元の写真からの変更。CC BY・CC BY-SA では、変更したことを示す */
export const PHOTO_CHANGES = "長辺を1200px以下に縮小し、JPEG で圧縮した";

const BY_2 = "https://creativecommons.org/licenses/by/2.0";
const BY_2_5 = "https://creativecommons.org/licenses/by/2.5";
const BY_3 = "https://creativecommons.org/licenses/by/3.0";
const BY_4 = "https://creativecommons.org/licenses/by/4.0";
const BY_SA_2 = "https://creativecommons.org/licenses/by-sa/2.0";
const BY_SA_3 = "https://creativecommons.org/licenses/by-sa/3.0";
const BY_SA_4 = "https://creativecommons.org/licenses/by-sa/4.0";
const CC0 = "https://creativecommons.org/publicdomain/zero/1.0";
const COMMONS = "https://commons.wikimedia.org/wiki/File:";
const FLICKR = "https://www.flickr.com/photos/";

export const PHOTO_CREDITS: PhotoCredit[] = [
  {
    path: "/images/spots/hakuba-01.jpg",
    subject: "白馬塩の道温泉 倉下の湯",
    author: "Qurren",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Kurashita_no_yu.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/hakuba-02.jpg",
    subject: "青鬼集落",
    author: "くろふね",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E9%9D%92%E9%AC%BC%E9%9B%86%E8%90%BD_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/hakuba-03.jpg",
    subject: "大出公園",
    author: "くろふね",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E5%A4%A7%E5%87%BA%E5%90%8A%E6%A9%8B_-_panoramio_(4).jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/hakuba-04.jpg",
    subject: "姫川源流自然探勝園",
    author: "くろふね",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E5%A7%AB%E5%B7%9D%E6%BA%90%E6%B5%81_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/hakuba-06.jpg",
    subject: "貞麟寺",
    author: "wakaba-shinshu",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${FLICKR}154568645@N04/34658438162`,
    sourceName: "Flickr",
  },
  {
    path: "/images/spots/omachi-01.jpg",
    subject: "塩の道ちょうじや",
    author: "Suikotei",
    license: "CC BY 4.0",
    licenseUrl: BY_4,
    sourceUrl: `${COMMONS}Hirabayashi-ke_Jyutaku_Shuoku.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/omachi-02.jpg",
    subject: "若一王子神社",
    author: "Furudanuki",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}%E8%8B%A5%E4%B8%80%E7%8E%8B%E5%AD%90%E7%A5%9E%E7%A4%BE%E9%B3%A5%E5%B1%85%E3%81%A8%E4%B8%89%E9%87%8D%E5%A1%94.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/omachi-03.jpg",
    subject: "ぽかぽかランド美麻",
    author: "小石川人晃",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Road_Station_Poka-Poka_Land_Miasa_01.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/omachi-06.jpg",
    subject: "居谷里湿原",
    author: "wakaba-shinshu",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${FLICKR}154568645@N04/34011672963`,
    sourceName: "Flickr",
  },
  {
    path: "/images/spots/omachi-07.jpg",
    subject: "中綱湖",
    author: "くろふね",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E4%B8%AD%E7%B6%B1%E6%B9%96_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/omachi-08.jpg",
    subject: "鷹狩山",
    author: "wakanmuri",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${FLICKR}13217899@N08/3507257327`,
    sourceName: "Flickr",
  },
  {
    path: "/images/spots/ikeda-01.jpg",
    subject: "池田八幡神社",
    author: "At1973",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}%E6%B1%A0%E7%94%B0%E5%85%AB%E5%B9%A1%E7%A5%9E%E7%A4%BE%E7%A4%BE%E6%AE%BF.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/ikeda-04.jpg",
    subject: "夢農場",
    author: "wakaba-shinshu",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${FLICKR}154568645@N04/34840653796`,
    sourceName: "Flickr",
  },
  {
    path: "/images/spots/ikeda-05.jpg",
    subject: "花紋大雪渓",
    author: "Qurren",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Daisekkei_Sake_Brewing_1.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/azumino-02.jpg",
    subject: "ほりでーゆ〜四季の郷",
    author: "Qurren",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Holiday_You_Shikinosato.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/azumino-04.jpg",
    subject: "貞享義民記念館",
    author: "小松宏彰",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}Kinenkan.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/azumino-06.jpg",
    subject: "御宝田遊水池",
    author: "アポロ2",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}%E5%BE%A1%E5%AE%9D%E7%94%B0%E9%81%8A%E6%B0%B4%E6%B1%A0.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/azumino-07.jpg",
    subject: "烏川渓谷緑地",
    author: "Qurren",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Karasu_River_view_from_Karasugawakeikokubashi-bridge.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/matsumoto-01.jpg",
    subject: "松本市はかり資料館",
    author: "663highland",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}250425_Matsumoto_City_Hakari_Museum_Matsumoto_Nagano_pref_Japan01s3.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/matsumoto-05.jpg",
    subject: "源智の井戸",
    author: "深志",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}%E6%BA%90%E6%99%BA%E3%81%AE%E4%BA%95%E6%88%B8.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/matsumoto-06.jpg",
    subject: "馬場家住宅",
    author: "Wiiii",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Babake_house_2010.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/matsumoto-07.jpg",
    subject: "弘法山古墳",
    author: "Saigen Jiro",
    license: "CC0",
    licenseUrl: CC0,
    sourceUrl: `${COMMONS}Koboyama_Kofun_zenkei.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/higashikawa-01.jpg",
    subject: "旭岳",
    author: "nAok0",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${COMMONS}Asahi-dake_(9099317042).jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/higashikawa-02.jpg",
    subject: "忠別湖",
    author: "pakku",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E5%BF%A0%E5%88%A5%E6%B9%96%EF%BC%88Lake_Tyubetsu%EF%BC%89_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/marumori-01.jpg",
    subject: "蔵の郷土館 齋理屋敷",
    author: "Mukasora",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Sairi_Residence_storehouse.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/nakanojo-02.jpg",
    subject: "奥四万湖",
    author: "Neruru",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}Shimagawa_Dam-Lake.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/nakanojo-03.jpg",
    subject: "沢渡温泉 共同浴場",
    author: "Qurren",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Sawatari_Onsen_public_bath.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/nakanojo-04.jpg",
    subject: "旧太子駅",
    author: "Qurren",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Oshi_Station_2017-08_1.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/nakanojo-05.jpg",
    subject: "野反湖",
    author: "Kohei Fujii",
    license: "CC BY-SA 2.0",
    licenseUrl: BY_SA_2,
    sourceUrl: `${COMMONS}Lake_Nozori_2011-07-23_(5989960888).jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/nakanojo-06.jpg",
    subject: "道の駅 霊山たけやま",
    author: "Puchi-masashi",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}R145-2020-102.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/ono-01.jpg",
    subject: "御清水",
    author: "Asturio Cantabrio",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Echizen-Ono_Oshozu_2021-07_ac.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/ono-02.jpg",
    subject: "武家屋敷旧内山家",
    author: "Asturio Cantabrio",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Former_Uchiyama_House_2021-07_ac.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/ono-03.jpg",
    subject: "亀山湯",
    author: "Asturio Cantabrio",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Echizen-Ono_Kameyama-yu_2021-07_ac.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/ono-04.jpg",
    subject: "真名鶴酒造",
    author: "Asturio Cantabrio",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Manatsuru_Brewery_2021-07_ac.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/ono-05.jpg",
    subject: "六呂師高原",
    author: "Alpsdake",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Rokuroshi_Highland_s2.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/ono-06.jpg",
    subject: "越前大野城",
    author: "Keisuke MAEDA",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Echizen_Ono_Castle.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takashima-01.jpg",
    subject: "白鬚神社",
    author: "Saigen Jiro",
    license: "CC0",
    licenseUrl: CC0,
    sourceUrl: `${COMMONS}Shirahige-jinja_(Takashima)_otorii.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takashima-02.jpg",
    subject: "メタセコイア並木",
    author: "Saigen Jiro",
    license: "CC0",
    licenseUrl: CC0,
    sourceUrl: `${COMMONS}Metasequoia_Namiki_in_2019.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takashima-03.jpg",
    subject: "針江生水の郷",
    author: "Kyoww",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Harie20160508a.JPG`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takashima-04.jpg",
    subject: "道の駅 くつき新本陣",
    author: "先従隗始",
    license: "CC0",
    licenseUrl: CC0,
    sourceUrl: `${COMMONS}Michinoeki_Kutsuki_Shinhonjin_20220228_03.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takahashi-01.jpg",
    subject: "備中松山城",
    author: "Ka23 13",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}BitchuMatsuyamaCastleKeep_Takahashi_Okayama_Japan_2015.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takahashi-02.jpg",
    subject: "吹屋ふるさと村",
    author: "Yoshio Kohara",
    license: "CC BY 3.0",
    licenseUrl: BY_3,
    sourceUrl: `${COMMONS}%E9%AB%98%E6%A2%81%E5%B8%82_%E5%90%B9%E5%B1%8B%E3%81%B5%E3%82%8B%E3%81%95%E3%81%A8%E6%9D%91_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takahashi-03.jpg",
    subject: "ベンガラ館",
    author: "663highland",
    license: "CC BY 2.5",
    licenseUrl: BY_2_5,
    sourceUrl: `${COMMONS}Bengarakan07s3200.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takahashi-04.jpg",
    subject: "頼久寺庭園",
    author: "Ka23 13",
    license: "CC BY-SA 4.0",
    licenseUrl: BY_SA_4,
    sourceUrl: `${COMMONS}Raikyuji_20180502_112529.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/takahashi-05.jpg",
    subject: "弥高山公園",
    author: "じぇい☆",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}Yatakayama-unkai002.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/taketa-01.jpg",
    subject: "岡城跡",
    author: "As6673",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}Okajoshi.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/taketa-02.jpg",
    subject: "白水ダム",
    author: "Tmizuk",
    license: "パブリックドメイン",
    licenseUrl: null,
    sourceUrl: `${COMMONS}Hakusui-Dam_full-view.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/taketa-03.jpg",
    subject: "七里田温泉館",
    author: "sk01",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}%E4%B8%83%E9%87%8C%E7%94%B0%E6%B8%A9%E6%B3%89%E4%B8%8B%E6%B9%AF_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/taketa-05.jpg",
    subject: "ラムネ温泉館",
    author: "sk01",
    license: "CC BY-SA 3.0",
    licenseUrl: BY_SA_3,
    sourceUrl: `${COMMONS}%E3%83%A9%E3%83%A0%E3%83%8D%E6%B8%A9%E6%B3%89_-_panoramio.jpg`,
    sourceName: "Wikimedia Commons",
  },
  {
    path: "/images/spots/taketa-06.jpg",
    subject: "くじゅう花公園",
    author: "TANAKA Juuyoh (田中十洋)",
    license: "CC BY 2.0",
    licenseUrl: BY_2,
    sourceUrl: `${COMMONS}Kuju_Flower_Park(3553982332).jpg`,
    sourceName: "Wikimedia Commons",
  },
];
